### ISSUE TITLE
Building static libraries without root ECALLs

### ISSUE THREAD

**Issue by dymil** [zhang-xin/SGX-CMake#9]
It looks like there isn't support in FindSGX.cmake for building a static library _exclusively_ to be used by an enclave, i.e., compiling source files into objects and statically linking them into archives using the SGX SDK libraries. For example, I don't think [sgx-gmp](https://github.com/intel/sgx-gmp) can be built using the commands defined here, forcing one to reinvent the wheel.

For our particular application, I tried doing just that and, because sgx_edger8r is always run, get errors about my EDL file (which will contain OCALLs only and thus exists more to be included in other EDLs than to stand alone) because "the enclave contains no public root ECALL".

**Comment by xzhangxa** [comment]
Hello @dymil 

Let me understand the requirement, is the case:
- there's a static lib to be linked into the enclave library, and the edl file of it doesn't have the ECALLs of it. These ECALLs are in another edl file that will be used finally when build the enclave;
- when compiling this static lib with `add_trusted_library()`, because it always calls sgx_edger8r, no ECALLs in edl file will be reported.

If so I think there're 2 solutions to this:
- confine edl definition, always define the edl file with all ECALL/OCALL of this lib. The original samples are like this so I assumed it's always the case;
- or modify `add_trusted_library()`, if no edl file provide we can skip sgx_edger8r (the compiler options are still used for this lib) as long as eventually when compiling the enclave the final edl file contains everything, like the samples do. I did experiment for this and it seems to work, though I don't use SGX everyday so not certain it's safe or not.

**Comment by dymil** [comment]
Regarding the requirements, the static lib will not have ECALLs at all, as its functions will be called from within the enclave. For that specific case, adding `--header-only` to the sgx_edger8r command worked; I had an almost-blank EDL file, so I suppose it was right not to generate a C source file... but looking at the [code](https://github.com/intel/linux-sgx/blob/04dd342ee794e6cda29366433fae73734cabc688/sdk/edger8r/linux/CodeGen.ml#L2404) which fails with the error, I believe it will fail again with the OCALLs added. I guess I'll raise this in the appropriate venue for the SDK, if I'm not missing something.

Still, separate from my specific version of the issue, the second solution is therefore what I had in mind, because that's more modular. It'd at least support cases (like sgx_gmp again) where the library solely interfaces with trusted code and thus needs no EDL file.

A user work-around worth mentioning is to have a dummy public ECALL.

EDIT: there also seems to be a contradiction between the [developer reference](https://01.org/intel-software-guard-extensions/downloads) and this project on how to make trusted libraries, with the former suggesting passing EDL files around (and trusting their Eclipse plugin, which I don't have).

For my specific case, I think the way to make the existing `edger8r` work is to follow the reference more: generate headers only (which this doesn't support?), and then indeed make sure the enclave EDL includes the library EDL, so that the actual definitions for the proxy/bridge functions can be generated later.

**Comment by xzhangxa** [comment]
Sorry for the delay, I've been out last week.

Thanks, your PR #10 fixes this problem by not passing EDL file to `add_trusted_library()`, so close issue now.
